[package]

name = "tiled"
version = "0.1.2"
description = "A rust crate for loading in maps created by the Tiled editor"
repository = "https://github.com/mattyhall/rs-tiled.git"
documentation = "http://rust-ci.org/mattyhall/rs-tiled/doc/tiled/"
readme = "README.md"
license = "MIT"
authors = ["Matthew Hall <matthew@quickbeam.me.uk>"]

[lib]
name = "tiled"
path = "src/lib.rs"

[[example]]
name = "example"
path = "examples/main.rs"

[dependencies]
flate2 = "*"
rustc-serialize = "*"

[dependencies.xml-rs]
git = "https://github.com/netvl/xml-rs.git"
