[package]

name = "tiled"
version = "0.1.0"
description = "A rust crate for loading in maps created by the Tiled editor"
readme = "README.md"
license = "MIT"
authors = ["Matthew Hall <matthew@quickbeam.me.uk>"]

[lib]
name = "tiled"
path = "src/lib.rs"

[[example]]
name = "example"
path = "examples/main.rs"

[dependencies]
flate2 = "~0.0.3"
rust-xml = "~0.1.1"
