[package]

name = "tiled"
version = "0.1.3"
description = "A rust crate for loading in maps created by the Tiled editor"
repository = "https://github.com/mattyhall/rs-tiled.git"
documentation = "http://rust-ci.org/mattyhall/rs-tiled/doc/tiled/"
readme = "README.md"
license = "MIT"
authors = ["Matthew Hall <matthew@quickbeam.me.uk>"]

[lib]
name = "tiled"
path = "src/lib.rs"

[[example]]
name = "example"
path = "examples/main.rs"

[dependencies]
flate2 = "0.2"
rustc-serialize = "0.3"
xml-rs = "0.1.26"
