[package]

name = "tiled"
version = "0.1.0"
authors = ["Matthew Hall <matthew@quickbeam.me.uk>"]

[lib]
name = "tiled"
path = "src/lib.rs"

[[example]]
name = "example"
path = "examples/main.rs"

[dependencies.rust-xml]
git = "https://github.com/netvl/rust-xml.git"

[dependencies.flate2]
git = "https://github.com/alexcrichton/flate2-rs"
