[package]

name = "tiled"
version = "0.0.1"
authors = ["Matthew Hall <matthew@quickbeam.me.uk>"]

[dependencies.rust-xml]
git = "https://github.com/netvl/rust-xml.git"

[dependencies.flate2]
git = "https://github.com/alexcrichton/flate2-rs"
